CREATE DATABASE IF NOT EXISTS gamesdb;

USE gamesdb;

DROP TABLE IF EXISTS customers; 
CREATE TABLE IF NOT EXISTS customers(
id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(20) NOT NULL,
age INT NOT NULL
);

DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products (
product_id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(60) NOT NULL,
price DECIMAL(6,2) NOT NULL,
stock INT NOT NULL,
release_date DATE NOT NULL
);

DROP TABLE IF EXISTS orders;
CREATE TABLE IF NOT EXISTS orders (
order_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
customer_id INT NOT NULL,
product_id INT NOT NULL,
date_placed DATE NOT NULL
);
